# Generated by Django 3.2.4 on 2021-07-02 10:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_videos',
            name='show_to',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
