# Generated by Django 3.2.4 on 2021-07-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_show_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Label',
        ),
    ]
